# Generated by Django 3.2.5 on 2022-01-04 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('color', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('puesto', models.CharField(max_length=80)),
                ('correo', models.EmailField(max_length=80)),
                ('contraseña', models.CharField(max_length=40, null=True)),
                ('imagen_empleado', models.ImageField(null=True, upload_to='empleados')),
                ('activo', models.CharField(max_length=2)),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.areas')),
            ],
        ),
        migrations.CreateModel(
            name='Encuestas',
            fields=[
                ('id_encuesta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_encuesta', models.DateField()),
                ('nombre_encuesta', models.CharField(max_length=80)),
                ('preguntas_multiples', models.CharField(max_length=80)),
                ('preguntas_abiertas', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=80)),
                ('marca', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=80)),
                ('color', models.CharField(max_length=80)),
                ('imagen', models.ImageField(null=True, upload_to='imagenesequipos')),
                ('pdf', models.FileField(null=True, upload_to='pdfequipos')),
                ('memoriaram', models.CharField(max_length=80)),
                ('procesador', models.CharField(max_length=80)),
                ('sistemaoperativo', models.CharField(max_length=80)),
                ('estado', models.CharField(max_length=80)),
                ('activo', models.CharField(max_length=2)),
                ('modelocargador', models.CharField(max_length=80, null=True)),
                ('fechaMant', models.DateField(null=True)),
                ('id_empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCS.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Impresoras',
            fields=[
                ('id_impresora', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=80)),
                ('numserie', models.CharField(max_length=80)),
                ('imagen', models.ImageField(null=True, upload_to='impresoras')),
                ('tipo', models.CharField(max_length=80)),
                ('enred', models.CharField(max_length=2)),
                ('ip', models.CharField(max_length=16, null=True)),
                ('estado', models.CharField(max_length=80)),
                ('activo', models.CharField(max_length=2)),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.areas')),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField(max_length=500)),
                ('tipo', models.CharField(max_length=3)),
                ('clasificacion', models.CharField(max_length=100)),
                ('id_encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.encuestas')),
            ],
        ),
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('id_programa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_version', models.CharField(max_length=80)),
                ('tipo', models.CharField(max_length=80)),
                ('licencia', models.CharField(max_length=80)),
                ('idioma', models.CharField(max_length=80)),
                ('sistemaoperativo_arq', models.CharField(max_length=80)),
                ('memoria_ram', models.CharField(max_length=80)),
                ('procesador', models.CharField(max_length=80)),
                ('imagenPrograma', models.ImageField(null=True, upload_to='programas')),
            ],
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.TextField(max_length=600)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.empleados')),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.preguntas')),
            ],
        ),
        migrations.CreateModel(
            name='Renovacion_Impresoras',
            fields=[
                ('id_renov_imp', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField()),
                ('fecha_renov', models.DateField()),
                ('id_impresora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.impresoras')),
            ],
        ),
        migrations.CreateModel(
            name='Renovacion_Equipos',
            fields=[
                ('id_renov_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField()),
                ('fecha_renov', models.DateField()),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.equipos')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramasArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.areas')),
                ('id_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.programas')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoPrograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.equipos')),
                ('id_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.programas')),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaEmpleadoResuelta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.empleados')),
                ('id_encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.encuestas')),
            ],
        ),
        migrations.CreateModel(
            name='Cartuchos',
            fields=[
                ('id_cartucho', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=80)),
                ('cantidad', models.IntegerField()),
                ('nuserie', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=80)),
                ('imagenCartucho', models.ImageField(null=True, upload_to='cartuchos')),
                ('id_impresora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.impresoras')),
            ],
        ),
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id_carta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('firma', models.ImageField(null=True, upload_to='firmas')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.empleados')),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.equipos')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarioMantenimiento',
            fields=[
                ('id_calmantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('operacion', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('observaciones', models.CharField(max_length=100)),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.equipos')),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(max_length=80)),
                ('id_objeto', models.IntegerField()),
                ('operacion', models.CharField(max_length=80)),
                ('fecha_hora', models.DateTimeField()),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.empleados')),
            ],
        ),
    ]
