# Generated by Django 3.2.5 on 2021-07-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartuchos',
            name='imagenCartucho',
            field=models.ImageField(null=True, upload_to='cartuchos'),
        ),
    ]
