# Generated by Django 3.2.7 on 2022-01-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestas',
            name='respuesta',
            field=models.TextField(max_length=100),
        ),
    ]
