# Generated by Django 3.2.5 on 2021-12-20 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuestas',
            fields=[
                ('id_encuesta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_encuesta', models.DateField()),
                ('nombre_encuesta', models.CharField(max_length=80)),
                ('preguntas_multiples', models.CharField(max_length=80)),
                ('preguntas_abiertas', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField(max_length=500)),
                ('tipo', models.CharField(max_length=3)),
                ('id_encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.encuestas')),
            ],
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.TextField(max_length=600)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.empleados')),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.preguntas')),
            ],
        ),
    ]
