# Generated by Django 3.2.5 on 2021-09-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0002_empleados_imagen_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendariomantenimiento',
            name='operacion',
            field=models.CharField(max_length=200),
        ),
    ]
