# Generated by Django 3.2.5 on 2021-07-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0002_cartuchos_imagencartucho'),
    ]

    operations = [
        migrations.AddField(
            model_name='programas',
            name='imagenPrograma',
            field=models.ImageField(null=True, upload_to='programas'),
        ),
    ]
