# Generated by Django 4.0.1 on 2022-01-25 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0003_discosduros_empleadosdiscosduros_memoriasusb_monitores_mouses_teclados_telefonos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestamosSistemas',
            fields=[
                ('id_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('tabla', models.CharField(max_length=100, null=True)),
                ('id_producto', models.CharField(max_length=4, null=True)),
                ('otro', models.CharField(max_length=100, null=True)),
                ('cantidad', models.IntegerField()),
                ('fecha_prestamo', models.DateField()),
                ('firma_entrega', models.ImageField(null=True, upload_to='firmasPrestamos')),
                ('devolucion', models.CharField(max_length=1)),
                ('fecha_entrega', models.DateField(null=True)),
                ('condiciones', models.CharField(max_length=100, null=True)),
                ('firma_devolucion', models.ImageField(null=True, upload_to='firmasPrestamos2')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.empleados')),
            ],
        ),
    ]
