# Generated by Django 3.2.5 on 2022-02-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0004_prestamossistemas'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleadosdiscosduros',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
