# Generated by Django 3.2.5 on 2022-02-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0005_empleadosdiscosduros_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamossistemas',
            name='estatus',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
