# Generated by Django 3.2.5 on 2022-04-11 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0006_prestamossistemas_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendariomantenimiento',
            name='id_impresora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCS.impresoras'),
        ),
        migrations.AlterField(
            model_name='calendariomantenimiento',
            name='id_equipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCS.equipos'),
        ),
    ]
