# Generated by Django 3.2.5 on 2022-04-12 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0007_auto_20220411_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoportesTecnicos',
            fields=[
                ('id_soporte', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_soporte', models.DateField()),
                ('equipo_soporte', models.CharField(max_length=50, null=True)),
                ('tabla', models.CharField(max_length=100)),
                ('operacion', models.CharField(max_length=100)),
                ('resuelto_interno', models.CharField(max_length=2, null=True)),
                ('resuelto_proveedor', models.CharField(max_length=50, null=True)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.empleados')),
            ],
        ),
    ]
