# Generated by Django 3.2.5 on 2022-04-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0008_soportestecnicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='soportestecnicos',
            name='observaciones',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='soportestecnicos',
            name='operacion',
            field=models.CharField(max_length=255),
        ),
    ]
