# Generated by Django 4.0.3 on 2022-04-25 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0010_implementacionsoluciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='HerramientasAlmacen',
            fields=[
                ('id_herramienta', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_herramienta', models.CharField(max_length=6)),
                ('nombre_herramienta', models.CharField(max_length=100)),
                ('descripcion_herramienta', models.TextField()),
                ('marca', models.CharField(max_length=50)),
                ('unidad', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=30)),
                ('imagen_herramienta', models.ImageField(null=True, upload_to='imagenesHerramientas')),
                ('estado_herramienta', models.CharField(max_length=2)),
                ('motivo_estado', models.CharField(max_length=200)),
                ('fecha_alta', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentosAlmacen',
            fields=[
                ('id_instrumento', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_instrumento', models.CharField(max_length=6)),
                ('nombre_instrumento', models.CharField(max_length=100)),
                ('descripcion_instrumento', models.TextField()),
                ('marca', models.CharField(max_length=50)),
                ('unidad', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=30)),
                ('imagen_instrumento', models.ImageField(null=True, upload_to='imagenesInstrumentos')),
                ('estado_instrumento', models.CharField(max_length=2)),
                ('motivo_estado', models.CharField(max_length=200)),
                ('fecha_alta', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PrestamosAlmacen',
            fields=[
                ('id_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField()),
                ('tipo', models.CharField(max_length=50, null=True)),
                ('proyecto_tarea', models.CharField(max_length=100, null=True)),
                ('observaciones', models.CharField(max_length=255)),
                ('tabla', models.CharField(max_length=100, null=True)),
                ('id_herramientaInstrumento', models.CharField(max_length=4, null=True)),
                ('otro', models.CharField(max_length=100, null=True)),
                ('cantidad_solicitada', models.IntegerField()),
                ('fecha_prestamo', models.DateField()),
                ('firma_prestamo', models.ImageField(null=True, upload_to='firmasPrestamosAlmacen')),
                ('fecha_devolucion', models.DateField(null=True)),
                ('firma_devolucion', models.ImageField(null=True, upload_to='firmasDevolucionAlmacen')),
                ('condiciones', models.CharField(max_length=100, null=True)),
                ('estatus', models.CharField(max_length=20, null=True)),
                ('id_empleado_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.empleados')),
            ],
        ),
    ]
