# Generated by Django 4.0.3 on 2022-04-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0011_herramientasalmacen_instrumentosalmacen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramientasalmacen',
            name='cantidad_existencia',
            field=models.IntegerField(null=True),
        ),
    ]
