# Generated by Django 4.0.3 on 2022-04-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0014_herramientasalmaceninactivas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamosalmacen',
            old_name='tabla',
            new_name='cantidades_solicitadas',
        ),
        migrations.RemoveField(
            model_name='prestamosalmacen',
            name='cantidad_solicitada',
        ),
        migrations.RemoveField(
            model_name='prestamosalmacen',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='prestamosalmacen',
            name='id_herramientaInstrumento',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
