# Generated by Django 4.0.3 on 2022-04-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0015_rename_tabla_prestamosalmacen_cantidades_solicitadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamosalmacen',
            name='fecha_requerimiento',
            field=models.DateField(null=True),
        ),
    ]
