# Generated by Django 4.0.3 on 2022-04-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0016_prestamosalmacen_fecha_requerimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamosalmacen',
            name='fecha_prestamo',
            field=models.DateField(null=True),
        ),
    ]
