# Generated by Django 4.0.4 on 2022-05-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0017_alter_prestamosalmacen_fecha_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramientasalmacen',
            name='costo',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='herramientasalmacen',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='herramientasalmaceninactivas',
            name='enInventario',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
