# Generated by Django 4.0.4 on 2022-05-09 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0018_herramientasalmacen_costo_herramientasalmacen_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicionCompraAlmacen',
            fields=[
                ('id_requi', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_requerida', models.IntegerField()),
                ('fehca_requi', models.DateField()),
                ('estatus_requi', models.CharField(max_length=30)),
                ('id_empleado_solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCS.empleados')),
                ('id_herramienta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCS.herramientasalmacen')),
                ('id_prestamo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCS.prestamosalmacen')),
            ],
        ),
    ]
