# Generated by Django 4.0.4 on 2022-05-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0019_requisicioncompraalmacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramientasalmacen',
            name='orden_compra_evidence',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='herramientasalmacen',
            name='proveedor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
