# Generated by Django 4.0.4 on 2022-05-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0020_herramientasalmacen_orden_compra_evidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramientasalmacen',
            name='sku',
            field=models.CharField(max_length=100),
        ),
    ]
