# Generated by Django 4.0.4 on 2022-05-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0021_alter_herramientasalmacen_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicioncompraalmacen',
            name='fehca_requiEntrada',
            field=models.DateField(null=True),
        ),
    ]
