# Generated by Django 4.0.4 on 2022-05-23 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0023_herramientasalmacen_nombre_corto'),
    ]

    operations = [
        migrations.CreateModel(
            name='bajasAlmacen',
            fields=[
                ('id_baja', models.AutoField(primary_key=True, serialize=False)),
                ('motivo_baja', models.CharField(max_length=10)),
                ('explicacion_baja', models.TextField()),
                ('cantidad_baja', models.IntegerField()),
                ('fecha_solicitud_baja', models.DateField()),
                ('estatus_baja', models.CharField(max_length=30)),
                ('token', models.CharField(max_length=30)),
                ('fecha_baja', models.DateField()),
                ('id_herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCS.herramientasalmacen')),
            ],
        ),
        migrations.CreateModel(
            name='altasAlmacen',
            fields=[
                ('id_alta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_agregar', models.IntegerField()),
                ('stockActualizado', models.IntegerField()),
                ('fecha_solicitud_alta', models.DateField()),
                ('orden_compra_evidence_act', models.CharField(max_length=30, null=True)),
                ('proveedor_alta', models.CharField(max_length=100, null=True)),
                ('estatus_alta', models.CharField(max_length=30)),
                ('token', models.CharField(max_length=30)),
                ('fecha_alta', models.DateField()),
                ('id_herramienta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCS.herramientasalmacen')),
            ],
        ),
    ]
