# Generated by Django 4.0.4 on 2022-05-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0024_bajasalmacen_altasalmacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='altasalmacen',
            name='codigoActualizado',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
