# Generated by Django 4.0.4 on 2022-05-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0025_altasalmacen_codigoactualizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altasalmacen',
            name='fecha_alta',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='altasalmacen',
            name='token',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
