# Generated by Django 4.0.4 on 2022-05-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0026_alter_altasalmacen_fecha_alta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='altasalmacen',
            old_name='token',
            new_name='requi',
        ),
        migrations.RemoveField(
            model_name='altasalmacen',
            name='fecha_solicitud_alta',
        ),
        migrations.AlterField(
            model_name='altasalmacen',
            name='cantidad_agregar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='altasalmacen',
            name='codigoActualizado',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='altasalmacen',
            name='orden_compra_evidence_act',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='altasalmacen',
            name='proveedor_alta',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='altasalmacen',
            name='stockActualizado',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
