# Generated by Django 4.0.4 on 2022-05-25 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0027_rename_token_altasalmacen_requi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mochilas',
            fields=[
                ('id_mochila', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
                ('foto', models.ImageField(null=True, upload_to='mouses')),
                ('activo', models.CharField(max_length=2)),
                ('id_empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCS.empleados')),
            ],
        ),
    ]
