# Generated by Django 4.0.4 on 2022-05-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0028_mochilas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mochilas',
            name='foto',
            field=models.ImageField(null=True, upload_to='mochilas'),
        ),
    ]
