# Generated by Django 4.0.4 on 2022-05-26 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0029_alter_mochilas_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celulares',
            fields=[
                ('id_celular', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('tipo_cargador', models.CharField(max_length=20, null=True)),
                ('modelo_cargador', models.CharField(max_length=40, null=True)),
                ('ram', models.IntegerField()),
                ('numero_setie', models.CharField(max_length=40, null=True)),
                ('numero_imei', models.CharField(max_length=40, null=True)),
                ('foto', models.ImageField(null=True, upload_to='mochilas')),
                ('estado', models.CharField(max_length=30)),
                ('activo', models.CharField(max_length=2)),
                ('id_empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appCS.empleados')),
            ],
        ),
    ]
