# Generated by Django 4.0.4 on 2022-05-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0030_celulares'),
    ]

    operations = [
        migrations.AddField(
            model_name='celulares',
            name='en_plan',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='celulares',
            name='fecha_contratacion_plan',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='celulares',
            name='fecha_contratacion_plan_final',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='celulares',
            name='telefono',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
