# Generated by Django 4.0.4 on 2022-05-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0031_celulares_en_plan_celulares_fecha_contratacion_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='celulares',
            name='compañia',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='celulares',
            name='nombre_plan',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
