# Generated by Django 4.0.4 on 2022-05-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCS', '0032_celulares_compañia_celulares_nombre_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celulares',
            name='fecha_contratacion_plan_final',
        ),
        migrations.AddField(
            model_name='celulares',
            name='meses_plan',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='celulares',
            name='foto',
            field=models.ImageField(null=True, upload_to='celulares'),
        ),
    ]
